package com.depthscanner3d.app.export;

import com.depthscanner3d.app.scan.PointSample;
import com.depthscanner3d.app.scan.ScanSnapshot;

import java.io.BufferedOutputStream;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public final class ScanArchiveExporter {
    private static final float INITIAL_MESH_VOXEL_SIZE_METERS = 0.0225f;
    private static final int MAX_MESH_CELLS = 28_000;
    private static final int MAX_MESH_REBUILD_ATTEMPTS = 20;
    private static final DateTimeFormatter ISO_FORMAT =
            DateTimeFormatter.ISO_INSTANT.withZone(ZoneOffset.UTC);

    private ScanArchiveExporter() {
    }

    public static ExportResult export(OutputStream destination, ScanSnapshot snapshot)
            throws IOException {
        if (snapshot.points().isEmpty()) {
            throw new IllegalArgumentException("Scan contains no points");
        }

        MeshData mesh = buildMesh(snapshot.points());
        try (ZipOutputStream zip = new ZipOutputStream(
                new BufferedOutputStream(destination), StandardCharsets.UTF_8)) {
            writePly(zip, snapshot.points());
            writePointObj(zip, snapshot.points());
            int meshTriangles = writeMeshObj(zip, mesh);
            writeMeshStl(zip, mesh);
            writeMetadata(zip, snapshot, mesh, meshTriangles);
            writeArchiveReadme(zip, mesh, meshTriangles);
            zip.finish();
            return new ExportResult(
                    snapshot.points().size(),
                    mesh.cells().size(),
                    meshTriangles,
                    mesh.voxelSizeMeters()
            );
        }
    }

    private static void writePly(ZipOutputStream zip, List<PointSample> points)
            throws IOException {
        zip.putNextEntry(new ZipEntry("scan_points.ply"));
        BufferedWriter writer = writer(zip);
        writer.write("ply\n");
        writer.write("format ascii 1.0\n");
        writer.write("comment Generated by Depth Scanner 3D\n");
        writer.write("element vertex " + points.size() + "\n");
        writer.write("property float x\n");
        writer.write("property float y\n");
        writer.write("property float z\n");
        writer.write("property uchar red\n");
        writer.write("property uchar green\n");
        writer.write("property uchar blue\n");
        writer.write("end_header\n");
        for (PointSample point : points) {
            writer.write(String.format(Locale.US,
                    "%.6f %.6f %.6f %d %d %d%n",
                    point.x(), point.y(), point.z(),
                    point.red(), point.green(), point.blue()));
        }
        writer.flush();
        zip.closeEntry();
    }

    private static void writePointObj(ZipOutputStream zip, List<PointSample> points)
            throws IOException {
        zip.putNextEntry(new ZipEntry("scan_points.obj"));
        BufferedWriter writer = writer(zip);
        writer.write("# Colored OBJ point cloud generated by Depth Scanner 3D\n");
        writer.write("# Vertex colors use the common extension: v x y z r g b\n");
        writer.write("o scan_points\n");
        for (PointSample point : points) {
            writer.write(String.format(Locale.US,
                    "v %.6f %.6f %.6f %.5f %.5f %.5f%n",
                    point.x(), point.y(), point.z(),
                    point.red() / 255.0f,
                    point.green() / 255.0f,
                    point.blue() / 255.0f));
        }
        int index = 1;
        while (index <= points.size()) {
            writer.write("p");
            for (int i = 0; i < 256 && index <= points.size(); i++, index++) {
                writer.write(" " + index);
            }
            writer.write('\n');
        }
        writer.flush();
        zip.closeEntry();
    }

    private static int writeMeshObj(ZipOutputStream zip, MeshData mesh)
            throws IOException {
        zip.putNextEntry(new ZipEntry("scan_mesh.obj"));
        BufferedWriter writer = writer(zip);
        writer.write("# Local voxel surface mesh generated by Depth Scanner 3D\n");
        writer.write(String.format(Locale.US, "# Mesh voxel size: %.6f m%n",
                mesh.voxelSizeMeters()));
        writer.write("o scan_mesh\n");

        int vertexIndex = 1;
        int triangleCount = 0;
        for (Map.Entry<Cell, CellColor> entry : mesh.cells().entrySet()) {
            Cell cell = entry.getKey();
            CellColor color = entry.getValue();
            for (Face face : Face.values()) {
                if (mesh.cells().containsKey(cell.offset(face.dx, face.dy, face.dz))) {
                    continue;
                }
                float[][] corners = faceCorners(cell, mesh.voxelSizeMeters(), face);
                for (float[] corner : corners) {
                    writer.write(String.format(Locale.US,
                            "v %.6f %.6f %.6f %.5f %.5f %.5f%n",
                            corner[0], corner[1], corner[2],
                            color.red() / 255.0f,
                            color.green() / 255.0f,
                            color.blue() / 255.0f));
                }
                writer.write(String.format(Locale.US,
                        "f %d %d %d%n", vertexIndex, vertexIndex + 1, vertexIndex + 2));
                writer.write(String.format(Locale.US,
                        "f %d %d %d%n", vertexIndex, vertexIndex + 2, vertexIndex + 3));
                vertexIndex += 4;
                triangleCount += 2;
            }
        }
        writer.flush();
        zip.closeEntry();
        return triangleCount;
    }

    private static void writeMeshStl(ZipOutputStream zip, MeshData mesh)
            throws IOException {
        zip.putNextEntry(new ZipEntry("scan_mesh.stl"));
        BufferedWriter writer = writer(zip);
        writer.write("solid depth_scanner_3d\n");
        for (Cell cell : mesh.cells().keySet()) {
            for (Face face : Face.values()) {
                if (mesh.cells().containsKey(cell.offset(face.dx, face.dy, face.dz))) {
                    continue;
                }
                float[][] corners = faceCorners(cell, mesh.voxelSizeMeters(), face);
                writeStlTriangle(writer, face, corners[0], corners[1], corners[2]);
                writeStlTriangle(writer, face, corners[0], corners[2], corners[3]);
            }
        }
        writer.write("endsolid depth_scanner_3d\n");
        writer.flush();
        zip.closeEntry();
    }

    private static void writeStlTriangle(
            BufferedWriter writer,
            Face face,
            float[] a,
            float[] b,
            float[] c
    ) throws IOException {
        writer.write(String.format(Locale.US,
                "  facet normal %.1f %.1f %.1f%n", face.nx, face.ny, face.nz));
        writer.write("    outer loop\n");
        writer.write(String.format(Locale.US,
                "      vertex %.6f %.6f %.6f%n", a[0], a[1], a[2]));
        writer.write(String.format(Locale.US,
                "      vertex %.6f %.6f %.6f%n", b[0], b[1], b[2]));
        writer.write(String.format(Locale.US,
                "      vertex %.6f %.6f %.6f%n", c[0], c[1], c[2]));
        writer.write("    endloop\n");
        writer.write("  endfacet\n");
    }

    private static void writeMetadata(
            ZipOutputStream zip,
            ScanSnapshot snapshot,
            MeshData mesh,
            int meshTriangles
    ) throws IOException {
        zip.putNextEntry(new ZipEntry("scan_metadata.json"));
        BufferedWriter writer = writer(zip);
        Bounds bounds = calculateBounds(snapshot.points());
        String started = snapshot.startedAtEpochMillis() > 0
                ? ISO_FORMAT.format(Instant.ofEpochMilli(snapshot.startedAtEpochMillis()))
                : null;
        writer.write("{\n");
        writer.write("  \"generator\": \"Depth Scanner 3D\",\n");
        writer.write("  \"format_version\": 1,\n");
        writer.write("  \"units\": \"meters\",\n");
        writer.write("  \"scan_started_utc\": "
                + (started == null ? "null" : "\"" + started + "\"") + ",\n");
        writer.write("  \"point_count\": " + snapshot.points().size() + ",\n");
        writer.write("  \"integrated_depth_frames\": "
                + snapshot.integratedDepthFrames() + ",\n");
        writer.write(String.format(Locale.US,
                "  \"capture_voxel_size_m\": %.6f,%n",
                snapshot.captureVoxelSizeMeters()));
        writer.write(String.format(Locale.US,
                "  \"minimum_confidence\": %.4f,%n",
                snapshot.minimumConfidence()));
        writer.write(String.format(Locale.US,
                "  \"depth_range_m\": [%.4f, %.4f],%n",
                snapshot.minimumDepthMeters(), snapshot.maximumDepthMeters()));
        writer.write(String.format(Locale.US,
                "  \"mesh_voxel_size_m\": %.6f,%n", mesh.voxelSizeMeters()));
        writer.write("  \"mesh_cell_count\": " + mesh.cells().size() + ",\n");
        writer.write("  \"mesh_triangle_count\": " + meshTriangles + ",\n");
        writer.write(String.format(Locale.US,
                "  \"bounds_min_m\": [%.6f, %.6f, %.6f],%n",
                bounds.minX, bounds.minY, bounds.minZ));
        writer.write(String.format(Locale.US,
                "  \"bounds_max_m\": [%.6f, %.6f, %.6f]%n",
                bounds.maxX, bounds.maxY, bounds.maxZ));
        writer.write("}\n");
        writer.flush();
        zip.closeEntry();
    }

    private static void writeArchiveReadme(
            ZipOutputStream zip,
            MeshData mesh,
            int triangleCount
    ) throws IOException {
        zip.putNextEntry(new ZipEntry("README_RU.txt"));
        BufferedWriter writer = writer(zip);
        writer.write("DEPTH SCANNER 3D — СОДЕРЖИМОЕ ЭКСПОРТА\n\n");
        writer.write("scan_points.ply — основное цветное облако точек в метрах.\n");
        writer.write("scan_points.obj — облако точек OBJ с расширением цвета вершин.\n");
        writer.write("scan_mesh.obj — локально построенная треугольная voxel-сетка.\n");
        writer.write("scan_mesh.stl — та же сетка для программ 3D-печати.\n");
        writer.write("scan_metadata.json — параметры, размеры и статистика скана.\n\n");
        writer.write(String.format(Locale.US,
                "Voxel-сетка: %.2f мм; треугольников: %d.%n",
                mesh.voxelSizeMeters() * 1000.0f, triangleCount));
        writer.write("Локальная сетка является черновой и может быть ступенчатой. ");
        writer.write("Для гладкой модели используйте scan_points.ply в CloudCompare, ");
        writer.write("MeshLab, Blender/Open3D или сервере reconstruction-server из проекта.\n");
        writer.flush();
        zip.closeEntry();
    }

    private static MeshData buildMesh(List<PointSample> points) {
        float voxelSize = INITIAL_MESH_VOXEL_SIZE_METERS;
        Map<Cell, MutableColor> mutableCells = null;
        for (int attempt = 0; attempt < MAX_MESH_REBUILD_ATTEMPTS; attempt++) {
            mutableCells = voxelize(points, voxelSize);
            if (mutableCells.size() <= MAX_MESH_CELLS) {
                break;
            }
            voxelSize *= 1.30f;
        }
        if (mutableCells == null) {
            mutableCells = new HashMap<>();
        }

        closeSingleVoxelGaps(mutableCells);
        Map<Cell, CellColor> result = new HashMap<>(mutableCells.size());
        for (Map.Entry<Cell, MutableColor> entry : mutableCells.entrySet()) {
            result.put(entry.getKey(), entry.getValue().average());
        }
        return new MeshData(result, voxelSize);
    }

    private static Map<Cell, MutableColor> voxelize(List<PointSample> points, float voxelSize) {
        Map<Cell, MutableColor> cells = new HashMap<>();
        for (PointSample point : points) {
            Cell cell = new Cell(
                    (int) Math.floor(point.x() / voxelSize),
                    (int) Math.floor(point.y() / voxelSize),
                    (int) Math.floor(point.z() / voxelSize)
            );
            cells.computeIfAbsent(cell, ignored -> new MutableColor())
                    .add(point.red(), point.green(), point.blue());
        }
        return cells;
    }

    private static void closeSingleVoxelGaps(Map<Cell, MutableColor> cells) {
        if (cells.size() > MAX_MESH_CELLS) {
            return;
        }
        Set<Cell> additions = new HashSet<>();
        List<Cell> original = new ArrayList<>(cells.keySet());
        int[][] axes = {{1, 0, 0}, {0, 1, 0}, {0, 0, 1}};
        for (Cell cell : original) {
            for (int[] axis : axes) {
                Cell middle = cell.offset(axis[0], axis[1], axis[2]);
                Cell opposite = cell.offset(axis[0] * 2, axis[1] * 2, axis[2] * 2);
                if (!cells.containsKey(middle) && cells.containsKey(opposite)) {
                    additions.add(middle);
                }
            }
        }
        int remainingCapacity = Math.max(0, MAX_MESH_CELLS - cells.size());
        for (Cell addition : additions) {
            if (remainingCapacity <= 0) {
                break;
            }
            MutableColor color = averageNeighborColor(cells, addition);
            if (cells.putIfAbsent(addition, color) == null) {
                remainingCapacity--;
            }
        }
    }

    private static MutableColor averageNeighborColor(Map<Cell, MutableColor> cells, Cell cell) {
        MutableColor result = new MutableColor();
        for (Face face : Face.values()) {
            MutableColor neighbor = cells.get(cell.offset(face.dx, face.dy, face.dz));
            if (neighbor != null) {
                CellColor color = neighbor.average();
                result.add(color.red(), color.green(), color.blue());
            }
        }
        if (result.count == 0) {
            result.add(160, 190, 220);
        }
        return result;
    }

    private static float[][] faceCorners(Cell cell, float size, Face face) {
        float minX = cell.x * size;
        float minY = cell.y * size;
        float minZ = cell.z * size;
        float maxX = minX + size;
        float maxY = minY + size;
        float maxZ = minZ + size;
        return switch (face) {
            case POS_X -> new float[][]{
                    {maxX, minY, minZ}, {maxX, maxY, minZ},
                    {maxX, maxY, maxZ}, {maxX, minY, maxZ}
            };
            case NEG_X -> new float[][]{
                    {minX, minY, maxZ}, {minX, maxY, maxZ},
                    {minX, maxY, minZ}, {minX, minY, minZ}
            };
            case POS_Y -> new float[][]{
                    {minX, maxY, maxZ}, {maxX, maxY, maxZ},
                    {maxX, maxY, minZ}, {minX, maxY, minZ}
            };
            case NEG_Y -> new float[][]{
                    {minX, minY, minZ}, {maxX, minY, minZ},
                    {maxX, minY, maxZ}, {minX, minY, maxZ}
            };
            case POS_Z -> new float[][]{
                    {minX, minY, maxZ}, {maxX, minY, maxZ},
                    {maxX, maxY, maxZ}, {minX, maxY, maxZ}
            };
            case NEG_Z -> new float[][]{
                    {maxX, minY, minZ}, {minX, minY, minZ},
                    {minX, maxY, minZ}, {maxX, maxY, minZ}
            };
        };
    }

    private static Bounds calculateBounds(List<PointSample> points) {
        PointSample first = points.get(0);
        Bounds bounds = new Bounds(
                first.x(), first.y(), first.z(),
                first.x(), first.y(), first.z()
        );
        for (int i = 1; i < points.size(); i++) {
            PointSample point = points.get(i);
            bounds.minX = Math.min(bounds.minX, point.x());
            bounds.minY = Math.min(bounds.minY, point.y());
            bounds.minZ = Math.min(bounds.minZ, point.z());
            bounds.maxX = Math.max(bounds.maxX, point.x());
            bounds.maxY = Math.max(bounds.maxY, point.y());
            bounds.maxZ = Math.max(bounds.maxZ, point.z());
        }
        return bounds;
    }

    private static BufferedWriter writer(ZipOutputStream zip) {
        return new BufferedWriter(new OutputStreamWriter(zip, StandardCharsets.UTF_8), 64 * 1024);
    }

    public static final class ExportResult {
        private final int pointCount;
        private final int meshCellCount;
        private final int meshTriangleCount;
        private final float meshVoxelSizeMeters;

        public ExportResult(
                int pointCount,
                int meshCellCount,
                int meshTriangleCount,
                float meshVoxelSizeMeters
        ) {
            this.pointCount = pointCount;
            this.meshCellCount = meshCellCount;
            this.meshTriangleCount = meshTriangleCount;
            this.meshVoxelSizeMeters = meshVoxelSizeMeters;
        }

        public int pointCount() { return pointCount; }
        public int meshCellCount() { return meshCellCount; }
        public int meshTriangleCount() { return meshTriangleCount; }
        public float meshVoxelSizeMeters() { return meshVoxelSizeMeters; }

        @Override
        public String toString() {
            return "ExportResult{"
                    + "pointCount=" + pointCount
                    + ", meshCellCount=" + meshCellCount
                    + ", meshTriangleCount=" + meshTriangleCount
                    + ", meshVoxelSizeMeters=" + meshVoxelSizeMeters
                    + '}';
        }
    }

    private static final class MeshData {
        private final Map<Cell, CellColor> cells;
        private final float voxelSizeMeters;

        MeshData(Map<Cell, CellColor> cells, float voxelSizeMeters) {
            this.cells = cells;
            this.voxelSizeMeters = voxelSizeMeters;
        }

        Map<Cell, CellColor> cells() { return cells; }
        float voxelSizeMeters() { return voxelSizeMeters; }
    }

    private static final class Cell {
        private final int x;
        private final int y;
        private final int z;

        Cell(int x, int y, int z) {
            this.x = x;
            this.y = y;
            this.z = z;
        }

        Cell offset(int dx, int dy, int dz) {
            return new Cell(x + dx, y + dy, z + dz);
        }

        @Override
        public boolean equals(Object other) {
            if (this == other) return true;
            if (!(other instanceof Cell)) return false;
            Cell cell = (Cell) other;
            return x == cell.x && y == cell.y && z == cell.z;
        }

        @Override
        public int hashCode() {
            int result = Integer.hashCode(x);
            result = 31 * result + Integer.hashCode(y);
            result = 31 * result + Integer.hashCode(z);
            return result;
        }
    }

    private static final class CellColor {
        private final int red;
        private final int green;
        private final int blue;

        CellColor(int red, int green, int blue) {
            this.red = red;
            this.green = green;
            this.blue = blue;
        }

        int red() { return red; }
        int green() { return green; }
        int blue() { return blue; }
    }

    private static final class MutableColor {
        long red;
        long green;
        long blue;
        int count;

        void add(int r, int g, int b) {
            red += r;
            green += g;
            blue += b;
            count++;
        }

        CellColor average() {
            int safeCount = Math.max(1, count);
            return new CellColor(
                    (int) (red / safeCount),
                    (int) (green / safeCount),
                    (int) (blue / safeCount)
            );
        }
    }

    private static final class Bounds {
        float minX;
        float minY;
        float minZ;
        float maxX;
        float maxY;
        float maxZ;

        Bounds(float minX, float minY, float minZ, float maxX, float maxY, float maxZ) {
            this.minX = minX;
            this.minY = minY;
            this.minZ = minZ;
            this.maxX = maxX;
            this.maxY = maxY;
            this.maxZ = maxZ;
        }
    }

    private enum Face {
        POS_X(1, 0, 0, 1, 0, 0),
        NEG_X(-1, 0, 0, -1, 0, 0),
        POS_Y(0, 1, 0, 0, 1, 0),
        NEG_Y(0, -1, 0, 0, -1, 0),
        POS_Z(0, 0, 1, 0, 0, 1),
        NEG_Z(0, 0, -1, 0, 0, -1);

        final int dx;
        final int dy;
        final int dz;
        final float nx;
        final float ny;
        final float nz;

        Face(int dx, int dy, int dz, float nx, float ny, float nz) {
            this.dx = dx;
            this.dy = dy;
            this.dz = dz;
            this.nx = nx;
            this.ny = ny;
            this.nz = nz;
        }
    }
}
